version: '2'
services:

  service-ball:
    build: ./service-ball
    ports: 
      - "8000:8000"

  service-ui:
    build: ./service-ui
    ports:
      - "80:80"

  browser:
    image: bh.cr/balenalabs/browser-aarch64 # where <arch> is one of aarch64, arm32 or amd64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    ports:
      - '5011' # management API (optional)
      - '35173' # Chromium debugging port (optional)
    environment:
      LAUNCH_URL: http://www.google.com
      KIOSK: 1
    # volumes:
    #   - 'settings:/data' # Only required if using PERSISTENT flag (see below)
