version: '2'
services:

  service-ball:
    build: ./service-ball
    ports: 
      - "8000:8000"

  service-ui:
    build: ./service-ui
    ports:
      - "80:80"

  browser:
    image: bh.cr/balenalabs/browser-armv7hf # where <arch> is one of aarch64, arm32 or amd64
    restart: unless-stopped
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    ports:
      - '5011' # management API (optional)
      - '35173' # Chromium debugging port (optional)
    environment:
      LAUNCH_URL: http://service-ui/
      KIOSK: 1
      SHOW_CURSOR: 0
      ENABLE_GPU: 1
      # WINDOW_SIZE: 1280,1024
    # volumes:
    #   - 'settings:/data' # Only required if using PERSISTENT flag (see below)
